<?php

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_NODE_FORM_alter().
 */
function hide_pub_revs_form_node_form_alter(&$form, FormStateInterface $form_state) {
  if (_hide_pub_revs_bypass()) {
    return;
  }
  $form['status']['#access'] = FALSE;
  $form['revision_information']['#access'] = FALSE;
  $form['revision']['#access'] = FALSE;
  $form['revision_log']['#access'] = FALSE;
}

/**
 * Implements hook_form_alter().
 */
function hide_pub_revs_form_node_type_add_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if (_hide_pub_revs_bypass()) {
    return;
  }

  $form['workflow']['#access'] = FALSE;
  $form['workflow']['options'] = [
    '#type' => 'value',
    '#value' => [
      'status' => TRUE,
      'promote' => FALSE,
      'sticky' => FALSE,
      'revision' => FALSE,
    ],
  ];
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function hide_pub_revs_form_node_type_edit_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if (_hide_pub_revs_bypass()) {
    return;
  }
  $form['workflow']['#access'] = FALSE;
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function hide_pub_revs_form_entity_form_display_edit_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if (_hide_pub_revs_bypass()) {
    return;
  }

  // Note: #access=FALSE does not hide this row so we have to unset.
  unset($form["fields"]["status"]);

  $form['#fields'] = array_filter($form['#fields'], function ($value) {
    return 'status' !== $value;
  });
}

/**
 * @return bool
 *   True if the UI should present.
 */
function _hide_pub_revs_bypass(): bool {
  return \Drupal::currentUser()->id() == 1;
}
